TrackYourFlight_App/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('auth_Service.urls')),
    path('flights/', include('flight_Service.urls'))
]

auth_Service/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = 'authapp'

urlpatterns = [
	
	path('signup',views.RegisterUser,name='register_user'),
	path('signin',views.LoginUser,name='login_user'),
	path('signout',views.LogoutUser,name='logout_user')

]

flight_Service/urls.py
from django.urls import path
from . import views
from django.views.generic import RedirectView

app_name = 'flightapp'

urlpatterns = [
	
	path('search',views.FlightSearch, name='homepage'),
	path('airlinesList',views.GetAirLinesList, name='airlinesList'),
	path('searchflightdata/', views.FlightSearchResult, name='flightsearchdata'),
	path('subscribe/', views.SubscribeToNotification, name='subscribe'),
	path('getallflightsdata/', views.GetAllFlighstData, name='fetchflightdata')
]

auth_Service/models.py
from django.db import models

# Create your models here.

flight_Service/models.py
from django.db import models

# Create your models here.

auth_Service/controllers.py
from config import Config


class AuthController:

	def __init__(self):
		self.db_conn = Config.POSTGRESSQL_CONN

	def save_registration_form(self, register_data):
		query = '''insert into usermaster (username, firstname, lastname, email, phone ,password) 
					values ('{username}', '{firstname}', '{lastname}', '{email}','{phone}', '{password}')'''.format(**register_data)

		self.db_conn.write_db(query)

	def get_user_data(self, login_data):
		query = '''select * from usermaster where email = '{email}' and password = '{password}' '''.format(**login_data)
		result = self.db_conn.query_db_one(query)
		return result

	def get_users_subscribed_to_notified(self,airline,flightnumber):
		query = '''select * from subscriptions subs inner join usermaster usm on subs.user_id=usm.id
					where subs.sub_airline=%s and subs.sub_flightnumber=%s '''
		result = self.db_conn.query_db(query, (airline, flightnumber))
		return result

auth_Service/views.py
from django.shortcuts import render,redirect
from .controllers import AuthController

def RegisterUser(request):

	if request.method=="GET":
		context={
			"title":"Register"
		}
		return render(request,'auth/register.html',context)


	if request.method=="POST":

		firstname = request.POST["firstname"]
		lastname = request.POST["lastname"]
		username = request.POST["username"]
		email = request.POST["email"]
		phone = request.POST["phone"]
		password = request.POST["password"]

		register_data = {

			"firstname":firstname,
			"lastname":lastname,
			"username":username,
			"email":email,
			"phone":phone,
			"password": password
		}

		AuthController().save_registration_form(register_data)
		
		return redirect('authapp:login_user')


def LoginUser(request):

	if request.method=="GET":
		context = {
			"title":"Login"
		}
		return render(request,'auth/login.html',context)

	if request.method=="POST":

		login_data = {"email":request.POST["email"],"password":request.POST["password"]}
		user_data = AuthController().get_user_data(login_data)
		if user_data:
			user_id = user_data.get('id')
			response = redirect('flightapp:homepage')
			response.set_cookie('userid', str(user_id))
			return response
		else:
			return render(request,'auth/login.html')


def LogoutUser(request):
	if request.method=="GET":
		response = redirect('flightapp:homepage')
		response.delete_cookie('userid')
		return response

flight_Service/controllers.py
from config import Config


class FlightController:

	def __init__(self):
		self.db_conn = Config.POSTGRESSQL_CONN


	def fetch_airlines_name(self):
		query='''select DISTINCT (airline) from flightdata'''
		result = self.db_conn.query_db(query)
		return result


	def get_flight_data(self,flight_search_filter):
		if(flight_search_filter["departure_airport"] and flight_search_filter["arrival_airport"] and flight_search_filter["departure_date"]):

			query = '''select * from flightdata fd full join subscriptions subs on fd.airline=subs.sub_airline
			 and fd.flightnumber=subs.sub_flightnumber where fd.departure='{departure_airport}' and fd.arrival='{arrival_airport}'
			and DATE_TRUNC('day', fd.departuredate) ='{departure_date}'  '''.format(**flight_search_filter)

		elif (flight_search_filter["airline_name"] and flight_search_filter["flight_number"]):
			query = '''select * from flightdata fd full join subscriptions subs on fd.airline=subs.sub_airline and 
			fd.flightnumber=subs.sub_flightnumber where fd.airline='{airline_name}' and fd.flightnumber='{flight_number}'  '''.format(**flight_search_filter)

		result = self.db_conn.query_db(query)
		return result


	def subscribeToNotify(self,flight_detail):
		if(flight_detail["sub_status"]=='1'):
			query = '''insert into subscriptions (user_id,sub_airline,sub_flightnumber,subscribe_status) values ('{userid}','{airline_name}','{flight_number}','1') '''.format(**flight_detail)

		elif (flight_detail["sub_status"]=='0'):
			query = '''delete from subscriptions where sub_airline='{airline_name}' and sub_flightnumber='{flight_number}' '''.format(**flight_detail)

		self.db_conn.write_db(query)


	def fetch_flight_data(self):

		query = '''select * from flightdata WHERE departuredate > CURRENT_TIMESTAMP'''
		result = self.db_conn.query_db(query)
		return result

flight_Service/views.py
from django.shortcuts import render,redirect
from .controllers import FlightController
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
import json


def FlightSearch(request):

	if request.method=="GET":
		context={
			"title":"Flight Search - Home",
			"userid": request.COOKIES.get('userid')
		}
		return render(request,'flight/search.html',context)


def GetAirLinesList(request):

	if request.method=="GET":
		airlinesList = FlightController().fetch_airlines_name()
		if airlinesList is not None:
			return JsonResponse({"airlines": airlinesList})


def FlightSearchResult(request):

	if request.method=="GET":
		departure_airport = request.GET.get('departure_airport', None)
		arrival_airport = request.GET.get('arrival_airport', None)
		departure_date = request.GET.get('departure_date', None)
		airline_name = request.GET.get('airline_name', None)
		flight_number = request.GET.get('flight_number', None)
		user_id = request.COOKIES.get('userid')

		search_param_data = {

			"departure_airport": departure_airport,
			"arrival_airport": arrival_airport,
			"departure_date": departure_date,
			"airline_name": airline_name,
			"flight_number":flight_number,
			"userid" : user_id

		}

		
		flight_data = FlightController().get_flight_data(search_param_data)
		for flight in flight_data:
			flight['userid'] = user_id
		print(flight_data)
		return JsonResponse(flight_data, safe=False)
		
@csrf_exempt
def SubscribeToNotification(request):

	if request.method=="POST":
		user_id = request.COOKIES.get('userid')
		if user_id:
			
			data = json.loads(request.body)
			print(data)
			flight_number = data.get('flight_number')
			airline_name = data.get('airline_name')
			sub_status = data.get('action')
			flight_detail = {
				"flight_number": flight_number,
				"airline_name": airline_name,
				"sub_status": sub_status,
				"userid" : user_id
			}
			if flight_number is None or  airline_name is None:
				return JsonResponse({"error": "Flight number or Airline Name is missing"}, status=400)

			FlightController().subscribeToNotify(flight_detail)
			return JsonResponse({"success": "Subscription successful"}, status=200)
		else:
			return JsonResponse({"error": "Please Login First"}, status=401)
	else:
		 return JsonResponse({"error": "Invalid request method"}, status=405)


@csrf_exempt
def GetAllFlighstData(request):

	if request.method=="GET":

		flight_data = FlightController().fetch_flight_data()

		return JsonResponse(list(flight_data), safe=False)

templates/flight/search.html
{% extends 'layout.html' %}
{% block content %}
<div class="flightsearch-container">
    <h1>Flight Status Search</h1>
    <div class="flight-search-tabs">
        <button class="tab-button active" data-tab="tab1">Search by Airport and Date</button>
        <button class="tab-button" data-tab="tab2">Search by Airline and Flight Number</button>
    </div>
    <div class="tab-content">
        <div id="tab1" class="tab active">
            <form id="search-by-airport-date">
                <label for="departure-airport">Departure Airport:</label>
                <input type="text" id="departure-airport" name="departure_airport" required>
                <label for="arrival-airport">Arrival Airport:</label>
                <input type="text" id="arrival-airport" name="arrival_airport" required>
                <label for="departure-date">Departure Date:</label>
                <input type="date" id="departure-date" name="departure_date" required>
                <button type="submit" class="search-button">Search</button>
            </form>
            <div id="results1"></div>
        </div>
        <div id="tab2" class="tab">
            <form id="search-by-airline-flight">
                <label for="airline-name">Airline Name:</label>
                <select id="airline-name" name="airline_name" required>
                    <!-- Options will be filled dynamically from the database -->
                </select>
                <label for="flight-number">Flight Number:</label>
                <input type="text" id="flight-number" name="flight_number" required>
                <button type="submit" class="search-button">Search</button>
            </form>
            <div id="results2"></div>
        </div>
    </div>
</div>
{% endblock %}

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
	<script type="text/javascript" src="https://code.jquery.com/jquery-1.7.1.min.js"></script>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="{% static 'js/script.js' %}"></script>
    <link rel="stylesheet" href="{% static 'main.css' %}">


	<title>{{ title }}</title>
</head>
<body>
{% csrf_token %}
	{% include 'navbar.html' %}

	{% block content %}
	{% endblock %}

</body>
</html>

templates/navbar.html
<nav class="navbar">
    <ul class="navbar-list">
        <li><a class="" href="{% url 'flightapp:homepage' %}">Home</a></li>
        {% if userid %}
            <li><a class="" href="{% url 'authapp:logout_user' %}">Logout</a></li>
        {% else %}
            <li><a class="" href="{% url 'authapp:login_user' %}">SignIn/Signup</a></li>
        {% endif %}
    </ul>
</nav>
